[[drone]]
id = 1
connected_node_ids = [10, 20]
pdr = 0.0

[[server]]
id = 10
connected_drone_ids = [1]
type = "Communication"

[[server]]
id = 20
connected_drone_ids = [1]
type = "Content"

[[client]]
id = 200
connected_drone_ids = []
